name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  PDF:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          path: out/cookbook.pdf

      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: cookbook
          path: out/cookbook.pdf
      
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out